### ISSUE TITLE
启用“自动幻灯片截屏”和“自动保存墨迹”后PPT偶尔无法翻页

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ChangSakura/Ink-Canvas#6]
## Description
启用“自动幻灯片截屏”和“自动保存墨迹”后PPT偶尔无法翻页

## Reproduction
打开这两项后找一个中长的PPT进入演示状态，进行大量批注后翻页

## Expected behavior
翻到下一页

## Screenshots
用的希沃，没键盘截屏

## Additional context
无

**Comment by muqiu-pika** [comment]
请问您的ica设置中是否已经关闭了自动将截屏分文件夹保存？目前已知这个设置在部分机型上无法使用，需要您手动关闭

**Comment by ChangSakura** [comment]
我这边暂时无法复现，请问出现该问题时是否有弹窗报错，或者软件安装目录下的 Log.txt 是否存在报错信息？如果有请麻烦提供一下，如果没有能否留意一下发生该问题时任务管理器中处理器和内存的占用情况？

**Comment by Qsgz2023ji5ban** [comment]
还真打开了分文件夹
关了就好了

发送自 Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
